// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvlqt_6OWE8jXCRibsv0LsEIYw-opXFm8',
    appId: '1:568103609242:web:78781a07595ba4df479023',
    messagingSenderId: '568103609242',
    projectId: 'disc-48936',
    authDomain: 'disc-48936.firebaseapp.com',
    storageBucket: 'disc-48936.appspot.com',
    measurementId: 'G-K4VCDVYBFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFShMCcGt3UtMQZgdlOEuXoVNAO3OeeZ0',
    appId: '1:568103609242:android:05aac51233d2849c479023',
    messagingSenderId: '568103609242',
    projectId: 'disc-48936',
    storageBucket: 'disc-48936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8RMcxa3eRurTAL5YIDNcAHx47d0gD8ws',
    appId: '1:568103609242:ios:f376b4e7b0d74271479023',
    messagingSenderId: '568103609242',
    projectId: 'disc-48936',
    storageBucket: 'disc-48936.appspot.com',
    androidClientId: '568103609242-k3mb639rkkevh5u4fra11soaste888ia.apps.googleusercontent.com',
    iosClientId: '568103609242-fv5ma6m0ussdp150lvfnnbdpj51mgkun.apps.googleusercontent.com',
    iosBundleId: 'com.example.disc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8RMcxa3eRurTAL5YIDNcAHx47d0gD8ws',
    appId: '1:568103609242:ios:7194aab0692b16a1479023',
    messagingSenderId: '568103609242',
    projectId: 'disc-48936',
    storageBucket: 'disc-48936.appspot.com',
    androidClientId: '568103609242-k3mb639rkkevh5u4fra11soaste888ia.apps.googleusercontent.com',
    iosClientId: '568103609242-4tr744sp8lknmdobkkpgg2dce43ajthp.apps.googleusercontent.com',
    iosBundleId: 'com.example.disc.RunnerTests',
  );
}
